# Generated by Django 4.1.1 on 2022-09-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_project_featured_image_alter_review_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="featured_image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
